# Generated by Django 3.2.8 on 2021-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_fortune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
